### ISSUE TITLE
LSRP_SERVER: Network connection lost.

### ISSUE THREAD

**Issue by KTBZay** [KTBZay/LSRPServer#9]
IsMajor: ✅ ;
Server is down

**Comment by KTBZay** [comment]
Added software updates, we are now overlooking to see if there is anymore issues. then we will fix the servers.

**Comment by OfficerZay412** [comment]
### **DEAR USERS**

_DUE TO THE WEATHER ELEMENTS IN THE SERVER REGION, WE HAVE TURNED THE SERVERS OVER TO PARTICLLY OPENED. THIS MEANS CERTAIN FEATURES WILL NOT WORK. PLEASE BARE WITH US THREW THESE DESPREATE MEASURES._

**Comment by KTBZay** [comment]
### SERVER LOGS
`We have added logs to the server github. you can review them at any time`

**Comment by KTBZay** [comment]
### Server Status
_Dear users the server status is still offline due to major bugs . please bare with us threw these desperate times_

**Comment by KTBZay** [comment]
Servers are back online
